name: Elixir CI

on:
  push:


jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.14.0'
        otp-version: '25.0.4'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
        mix deps.compile
        mix dialyzer --plt
    - name: Run format
      run: mix format --check-formatted
    - name: Run Credo
      run: mix credo
    - name: Run dialyzer
      run: mix dialyzer
    - name: Run tests
      run: mix test
    - name: mix clean
      run: mix clean
