name: Node CI 

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: assets
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"
          cache: 'yarn'
          cache-dependency-path: 'assets/yarn.lock'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
